[package]
name = "candle-cublaslt"
version = "0.2.2"
edition = "2021"

description = "CUBLASLt gemm for the candle ML framework."

[dependencies]
candle = { version = "0.3.0", package = "candle-core", features = ["cuda"]}
cudarc = { git = "https://github.com/OlivierDehaene/cudarc", rev = "61b35456ec7f72b5c123bb0cb5b04f6b0ab2a2a7", features = ["cublaslt", "f16"]}
half = { version = "2.3.1", features = ["num-traits"] }

